# Site settings
name: The Technical Mess
description: > # this means to ignore newlines until "baseurl:"
  In which I write about things related to my scientific work or general hacking.
  <br><br>
  Norwegian, PhD-student in Computational Physics, father, Linux hacker, eternal tinkerer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asmunder.github.io" # the base hostname & protocol for your site
github:  asmunder
bitbucket:  asmunder
figshare:  asmunder

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-61897985-1'
  
# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'thetechnicalmess'
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
